"""Fill the memo, evaluation page, and README measured blocks from harness JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SC = HERE / "source_coverage" / "results"
IS_ = HERE / "index_sensitivity" / "results"
PB = HERE / "prevalence_bounds" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _md(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    sc = _read(SC / "results.json")
    idx = _read(IS_ / "results.json")
    pb = _read(PB / "results.json")
    sc_table = "\n".join(
        line for line in _md(SC / "results.md").splitlines() if line.startswith("|")
    )
    idx_table = "\n".join(
        line for line in _md(IS_ / "results.md").splitlines() if line.startswith("|")
    )
    pb_table = "\n".join(
        line for line in _md(PB / "results.md").splitlines() if line.startswith("|")
    )
    filled = (
        template.replace("{{SC_N_COUNTIES}}", str(sc["n_counties"]))
        .replace("{{SC_N_PAIRS}}", str(sc["n_pairs"]))
        .replace("{{SC_TABLE}}", sc_table)
        .replace("{{SC_DECISION}}", str(sc["decision"]))
        .replace("{{IS_MIN_RHO}}", f"{idx['min_spearman']:.3f}")
        .replace("{{IS_N}}", str(idx["n_complete_for_correlation"]))
        .replace("{{IS_TABLE}}", idx_table)
        .replace("{{IS_DECISION}}", str(idx["decision"]))
        .replace("{{PB_N_WIDE}}", str(pb["n_wide"]))
        .replace("{{PB_RATIO}}", f"{pb['mcdowell_luxturna_ratio']:.1f}")
        .replace("{{PB_TABLE}}", pb_table)
        .replace("{{PB_DECISION}}", str(pb["decision"]))
    )
    return filled


def render_eval() -> str:
    sc = _md(SC / "results.md")
    idx = _md(IS_ / "results.md")
    pb = _md(PB / "results.md")
    idx_json = _read(IS_ / "results.json")
    return (
        "# Evaluation (Phase 0 baseline)\n\n"
        "Regenerated by `make eval` / `make research`. National coverage "
        "and live CMS freshness do not exist yet. The source-coverage, "
        "index-sensitivity, and prevalence-interval tables are the baseline "
        "any later warehouse must be reported against.\n\n"
        f"Min pairwise Spearman across weight schemes: "
        f"**{idx_json['min_spearman']:.3f}**. "
        f"Index needs rethinking: **{idx_json['needs_rethinking']}**.\n\n"
        f"{sc}\n\n{idx}\n\n{pb}\n"
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    readme_path = ROOT / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    sc = _read(SC / "results.json")
    idx = _read(IS_ / "results.json")
    pb = _read(PB / "results.json")
    body = (
        "| Measurement | Value | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Unusable sources | {', '.join(sc['unusable_sources']) or '(none)'} | "
        f"{sc['n_counties']} counties | Completeness < 0.80 or stale |\n"
        f"| Min Spearman across weights | {idx['min_spearman']:.3f} | "
        f"{idx['n_complete_for_correlation']} | "
        f"{'Index needs rethinking' if idx['needs_rethinking'] else 'Stable'} |\n"
        f"| Wide prevalence pairs | {pb['n_wide']} | {pb['n_pairs']} | "
        f"McDowell × Luxturna ratio {pb['mcdowell_luxturna_ratio']:.1f}× |\n"
        "| Silent point estimate used | no | — | Intervals only |\n"
        "| National extract | Phase 2 | — | Live CMS/Census unmeasured |\n"
    )
    text = _replace_block(text, "<!-- EVAL_TABLE_BEGIN -->", "<!-- EVAL_TABLE_END -->", body)
    readme_path.write_text(text, encoding="utf-8")


def main() -> None:
    memo = render_memo()
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(memo, encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    if (ROOT / "README.md").exists():
        patch_readme()
    print("wrote docs/phase-0/research-memo.md, docs/EVALUATION.md, README results block")


if __name__ == "__main__":
    main()
